### ISSUE TITLE
lager can not work in emq2.0 

### ISSUE THREAD

**Issue by congleetea** [emqtt/emqttd-relx#2]
when i update emqttd to emq2.0,  I did not change the configurations, but when i use lager:error,  it prints nothing.   (tested in ubuntu14.04)
Then I change the level to info:
`{lager, [
    {colored, true},
    {async_threshold, 5000},
    {error_logger_redirect, false},
    {crash_log, "log/emqttd_crash.log"},
    {handlers, [
        {lager_console_backend, info},
        %%NOTICE: Level >= error
        %%{lager_emqtt_backend, error},
        {lager_file_backend, [
            {formatter_config, [time, " ", pid, " [",severity,"] ", message, "\n"]},
            {file, "log/emqttd_error.log"},
            {level, info},
            {size, 104857600},
            {date, "$D0"},
            {count, 30}
        ]}
    ]}
 ]},
`

it also prints nothing.

**Comment by mobedu** [comment]
debian arm build error

1.  src/bson_binary.erl:55: illegal use of variable 'Name' in map
2. mongodb  illegal use of variable 'Id' in map
