### ISSUE TITLE
debian arm build error

### ISSUE THREAD

**Issue by mobedu** [emqtt/emqttd-relx#5]
erlang version: erlang/stable,now 1:17.3-dfsg-4 all
deps/bson/src/bson_binary.erl:55: illegal use of variable 'Name' in map
1. get_fields(Bin1, maps:put(Name, Value, Acc));

deps/mongodb/src/connection/mc_worker.erl
1. 128 line: URStorage = RequestStorage#{Id => RespFun},
2.           URStorage = RequestStorage(maps:put(Id, RespFun, maps:new())),
3. 152 line: UReqStor = ReqStor#{Id => RespFun},
4.           UReqStor = ReqStor(maps:put(Id, RespFun, maps:new())),

**Comment by turtleDeng** [comment]
Erlang vm version, please upgrade to erlang R18

**Comment by mobedu** [comment]
root@Buysz_Pi:/usr/local/emqttd# ./bin/emqttd start
root@Buysz_Pi:/usr/local/emqttd# ./bin/emqttd_ctl users add buysz 123123
RPC to 'emqttd@127.0.0.1' failed: {'EXIT',
                                   {undef,
                                    [{rand,uniform,[4294967295],[]},
                                     {emqttd_auth_username,salt,0,
                                      [{file,"src/emqttd_auth_username.erl"},
                                       {line,163}]},
                                     {emqttd_auth_username,hash,1,
                                      [{file,"src/emqttd_auth_username.erl"},
                                       {line,157}]},
                                     {emqttd_auth_username,add_user,2,
                                      [{file,"src/emqttd_auth_username.erl"},
                                       {line,83}]},
                                     {emqttd_auth_username,'-cli/1-fun-1-',2,
                                      [{file,"src/emqttd_auth_username.erl"},
                                       {line,51}]},
                                     {rpc,'-handle_call_call/6-fun-0-',5,
                                      [{file,"rpc.erl"},{line,205}]}]}}

**Comment by turtleDeng** [comment]
erlang vm version?

**Comment by mobedu** [comment]
R17/6.2   怎么升级成 R18 昨天yan研究了一下没闹明白

**Comment by turtleDeng** [comment]
You can refer to http://qqdenghaigui.iteye.com/blog/2197770 install erlang vm R18
