### ISSUE TITLE
Guide for adding new plugin

### ISSUE THREAD

**Issue by sudododo** [emqtt/emqttd-relx#6]
emqttd-relx is being used to make a build of the broker. It seems there is no instruction how to add new plugin to emqttd-relx and build it. Can someone help?

**Comment by turtleDeng** [comment]
1 step： Makefile add deps  new plugin
2 step：cp  plugin.conf to etc/plugins/
3 step：relx.config add {plugin_name, load}

**Comment by sudododo** [comment]
@turtleDeng It works. Thanks!

**Comment by emqplus** [comment]
I updated the Plugin Development Guide : http://emqtt.io/docs/v2/plugins.html#plugin-development-guide
