### ISSUE TITLE
compile failed in linux32

### ISSUE THREAD

**Issue by kissthink** [emqtt/emqttd-relx#8]
make[3]: Entering directory `/opt/emqttd-relx/deps/bson'
 DEPEND bson.d
 ERLC   bson.erl bson_binary.erl bson_schema.erl
src/bson_binary.erl:55: illegal use of variable 'Name' in map
make[4]: *** [ebin/bson.app] Error 1
make[3]: *** [app] Error 2
make[3]: Leaving directory `/opt/emqttd-relx/deps/bson'
make[2]: *** [deps] Error 2
make[2]: Leaving directory `/opt/emqttd-relx/deps/mongodb'
make[1]: *** [deps] Error 2
make[1]: Leaving directory `/opt/emqttd-relx/deps/emq_auth_mongo'
make: *** [deps] Error 2

**Comment by kissthink** [comment]
compiler info:

erlang-otp-17.4 

bash-4.2# erl -v
Erlang/OTP 17 [erts-6.3] [source] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V6.3  (abort with ^G)

**Comment by kissthink** [comment]
change erlang-otp-17.4   to 19.1 ,compiler success .
but run err:



bash-4.2# ./emqttd console
Exec: /opt/emqttd-relx/_rel/emqttd/erts-8.1/bin/erlexec -boot /opt/emqttd-relx/_rel/emqttd/releases/2.0/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd-relx/_rel/emqttd/erts-8.1/../lib -mnesia dir "/opt/emqttd-relx/_rel/emqttd/data/mnesia/emqttd@127.0.0.1" -config /opt/emqttd-relx/_rel/emqttd/data/configs/app.2016.11.13.13.37.01.config -args_file /opt/emqttd-relx/_rel/emqttd/data/configs/vm.2016.11.13.13.37.01.args -vm_args /opt/emqttd-relx/_rel/emqttd/data/configs/vm.2016.11.13.13.37.01.args -- console
Root: /opt/emqttd-relx/_rel/emqttd
/opt/emqttd-relx/_rel/emqttd
Erlang/OTP 19 [erts-8.1] [source] [smp:4:4] [async-threads:32] [kernel-poll:true]

starting emqttd on node 'emqttd@127.0.0.1'
emqttd ctl is starting...[ok]
emqttd hook is starting...[ok]
emqttd router is starting...[ok]
emqttd pubsub is starting...[ok]
emqttd stats is starting...[ok]
emqttd metrics is starting...[ok]
emqttd pooler is starting...[ok]
emqttd trace is starting...[ok]
emqttd client manager is starting...[ok]
emqttd session manager is starting...[ok]
emqttd session supervisor is starting...[ok]
emqttd wsclient supervisor is starting...[ok]
emqttd broker is starting...[ok]
emqttd alarm is starting...[ok]
emqttd mod supervisor is starting...[ok]
emqttd bridge supervisor is starting...[ok]
emqttd access control is starting...[ok]
emqttd system monitor is starting...[ok]
13:37:03.029 [error] CRASH REPORT Process <0.932.0> with 0 neighbours exited with reason: no match of right hand value undefined in emqttd_plugins:plugin/1 line 114 in application_master:init/4 line 134
13:37:03.030 [error] Mnesia down: 'emqttd@127.0.0.1'
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,undefined},[{emqttd_plugins,plugin,1,[{file,\"src/emqttd_plugins.erl\"},{line,114}]},{emqttd_plugins,'-list/0-lc$^0/1-0-',1,[{file,\"src/emqttd_plugins.erl\"},{line,100}]},{emqttd_plugins,'-list/0-lc$^0/1-0-',1,[{file,\"src/emqttd_plugins.erl\"},{line,100}]},{emqttd_plugins,list,0,[{file,\"src/emqttd_plugins.erl\"},{line,100}]},{emqttd_plugins,load_plugins,2,[{file,\"src/emqttd_plugins.erl\"},{line,72}]},{emqttd_app,start,2,[{file,\"src/emqttd_app.erl\"},{line,51}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,emqttd,{bad_return,{{emqttd_app,start,[normal,[]]},{'EXIT',{{badmatch,undefined},[{emqttd_plugins,plugin,1,[{file,"src/emqttd

Crash dump is being written to: log/crash.dump...done

**Comment by emqplus** [comment]
@kissthink, EMQ 2.0 requires Erlang/OTP R18 to build

**Comment by kissthink** [comment]
EMQ 2.0 requires Erlang/OTP R18 to build
yeah , building success , but running err !

===
emqttd system monitor is starting...[ok]
13:37:03.029 [error] CRASH REPORT Process <0.932.0> with 0 neighbours exited with reason: no match of right hand value undefined in emqttd_plugins:plugin/1 line 114 in application_master:init/4 line 134
13:37:03.030 [error] Mnesia down: 'emqttd@127.0.0.1'
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
